use actix_web::web;
use crate::handlers::{attendance_handler, auth_handler, dashboard_handler, employee_handler, group_handler, health_handler, leave_handler, location_handler, maintenance_handler, patrol_handler, profile_handler, shift_handler, shift_management_handler, wifi_handler};

pub fn init_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api")
            .route("/health", web::get().to(health_handler::health_check))
            .route("/login", web::post().to(auth_handler::login))
            .route("/register", web::post().to(auth_handler::register))
            .route("/attendance/enrollment-status", web::post().to(attendance_handler::check_enrollment))
            .route("/attendance/enroll-face", web::post().to(attendance_handler::enroll_face))
            .route("/attendance/enroll-fingerprint", web::post().to(attendance_handler::enroll_fingerprint))
            .route("/attendance/clock-in", web::post().to(attendance_handler::clock_in))
            .route("/attendance/logs", web::get().to(attendance_handler::get_all_attendances))
            .route("/employees", web::get().to(employee_handler::get_all_employees))
            .route("/employees", web::post().to(employee_handler::create_employee))
            .route("/employees/bulk", web::post().to(employee_handler::bulk_create_employees))
            .route("/employees/bulk-attendance", web::put().to(employee_handler::bulk_update_attendance))
            .route("/employees/{nik}", web::get().to(employee_handler::get_employee_by_nik))
            .route("/employees/{nik}", web::put().to(employee_handler::update_employee))
            .route("/employees/{nik}", web::delete().to(employee_handler::delete_employee))
            // Maintenance Routes
            .route("/maintenance/fix-attendance-requirements", web::post().to(maintenance_handler::fix_attendance_requirements))
            // Group Management Routes
            .route("/groups", web::get().to(group_handler::get_all_groups))
            .route("/groups", web::post().to(group_handler::create_group))
            .route("/groups/{id}", web::get().to(group_handler::get_group))
            .route("/groups/{id}", web::put().to(group_handler::update_group))
            .route("/groups/{id}", web::delete().to(group_handler::delete_group))
            // Profile Management Routes
            .route("/profile/{nik}", web::get().to(profile_handler::get_profile))
            .route("/profile", web::put().to(profile_handler::update_profile))
            .route("/profile/change-password", web::post().to(profile_handler::change_password))
            .route("/profile/upload-photo", web::post().to(profile_handler::upload_profile_photo))
            .route("/leave", web::post().to(leave_handler::submit_leave))
            .route("/leave", web::get().to(leave_handler::get_leaves))
            .route("/leave/status", web::put().to(leave_handler::update_leave_status))
            .route("/patrol/incident", web::post().to(patrol_handler::submit_incident))
            .route("/patrol/incidents", web::post().to(patrol_handler::submit_incident))
            .route("/patrol/incidents", web::get().to(patrol_handler::get_all_incidents))
            .route("/patrol/incidents/{nik}", web::get().to(patrol_handler::get_incidents_by_nik))
            .route("/patrol/incidents/{id}", web::put().to(patrol_handler::update_incident))
            .route("/patrol/incidents/{id}", web::delete().to(patrol_handler::delete_incident))
            // Checkpoint Reports
            .route("/patrol/checkpoint-reports", web::post().to(patrol_handler::create_checkpoint_report))
            .route("/patrol/checkpoint-reports", web::get().to(patrol_handler::get_checkpoint_reports))
            .route("/patrol/checkpoint-reports/{id}", web::get().to(patrol_handler::get_checkpoint_report))
            .route("/patrol/checkpoint-reports/{id}", web::put().to(patrol_handler::update_checkpoint_report))
            .route("/patrol/checkpoint-reports/{id}", web::delete().to(patrol_handler::delete_checkpoint_report))
            .route("/patrol/areas", web::get().to(patrol_handler::get_areas))
            .route("/patrol/areas", web::post().to(patrol_handler::create_area))
            .route("/patrol/areas/{id}", web::put().to(patrol_handler::update_area))
            .route("/patrol/areas/{id}", web::delete().to(patrol_handler::delete_area))
            .route("/patrol/checkpoints", web::post().to(patrol_handler::create_checkpoint))
            .route("/patrol/checkpoints", web::get().to(patrol_handler::get_checkpoints))
            .route("/patrol/checkpoints/{id}", web::put().to(patrol_handler::update_checkpoint))
            .route("/patrol/checkpoints/{id}", web::delete().to(patrol_handler::delete_checkpoint))
            .route("/patrol/assignments", web::post().to(patrol_handler::create_patrol_assignment))
            .route("/patrol/assignments", web::get().to(patrol_handler::get_patrol_assignments))
            .route("/patrol/assignments/{id}", web::put().to(patrol_handler::update_patrol_assignment))
            .route("/patrol/assignments/{id}", web::delete().to(patrol_handler::delete_patrol_assignment))
            .route("/patrol/status/active", web::get().to(patrol_handler::get_active_patrol_status))
            .route("/patrol/tracking/live", web::get().to(patrol_handler::get_live_tracking))
            .route("/patrol/scan", web::post().to(patrol_handler::scan_checkpoint))
            .route("/shift", web::post().to(shift_handler::create_shift))
            .route("/shift/list", web::post().to(shift_handler::get_shifts))
            .route("/shift/all", web::get().to(shift_handler::get_all_shifts))
            .route("/shift/status", web::put().to(shift_handler::update_shift_status))
            .route("/shift/stats/{nik}", web::get().to(shift_handler::get_shift_stats))
            .route("/shift/{shift_id}", web::delete().to(shift_handler::delete_shift))
            // Shift Management System Routes
            .route("/shift-tasks", web::get().to(shift_management_handler::get_all_shift_tasks))
            .route("/shift-tasks", web::post().to(shift_management_handler::create_shift_task))
            .route("/shift-tasks/{id}", web::get().to(shift_management_handler::get_shift_task))
            .route("/shift-tasks/{id}", web::put().to(shift_management_handler::update_shift_task))
            .route("/shift-tasks/{id}", web::delete().to(shift_management_handler::delete_shift_task))
            .route("/shift-tasks/{id}/groups", web::get().to(shift_management_handler::get_employee_groups))
            .route("/shift-tasks/{id}/groups", web::put().to(shift_management_handler::save_employee_groups))
            .route("/shift-tasks/{id}/available-employees", web::get().to(shift_management_handler::get_available_employees))
            .route("/shift-tasks/{id}/schedules/generate", web::post().to(shift_management_handler::generate_schedule))
            .route("/shift-tasks/{id}/schedules", web::get().to(shift_management_handler::get_schedules))
            .route("/shift-tasks/{id}/schedules/{date}", web::put().to(shift_management_handler::update_schedule))
            .route("/shift-tasks/{id}/schedules", web::delete().to(shift_management_handler::delete_schedules))
            // Dashboard Analytics Routes
            .route("/dashboard/analytics", web::get().to(dashboard_handler::get_dashboard_analytics))
            .route("/dashboard/overview", web::get().to(dashboard_handler::get_overview_only))
            .route("/dashboard/attendance", web::get().to(dashboard_handler::get_attendance_analytics))
            .route("/dashboard/patrol", web::get().to(dashboard_handler::get_patrol_analytics))
            .route("/dashboard/incidents", web::get().to(dashboard_handler::get_incident_analytics))
            .route("/dashboard/performance", web::get().to(dashboard_handler::get_performance_analytics))
            .route("/dashboard/locations", web::get().to(dashboard_handler::get_location_analytics))
            // WiFi Validation Routes
            .route("/wifi-settings", web::get().to(wifi_handler::get_wifi_settings))
            .route("/wifi-settings/all", web::get().to(wifi_handler::get_all_wifi_settings))
            .route("/wifi-settings/validate", web::post().to(wifi_handler::validate_wifi_ssid))
            .route("/wifi-settings", web::post().to(wifi_handler::create_wifi_setting))
            .route("/wifi-settings/{wifi_id}", web::patch().to(wifi_handler::update_wifi_setting))
            .route("/wifi-settings/{wifi_id}", web::put().to(wifi_handler::update_wifi_setting))
            .route("/wifi-settings/{wifi_id}", web::delete().to(wifi_handler::delete_wifi_setting))
            // Location Boundary Routes
            .route("/location-boundaries", web::get().to(location_handler::get_location_boundaries))
            .route("/location-boundaries/all", web::get().to(location_handler::get_all_location_boundaries))
            .route("/location-boundaries/validate", web::post().to(location_handler::validate_location))
            .route("/location-boundaries", web::post().to(location_handler::create_location_boundary))
            .route("/location-boundaries/{location_id}", web::patch().to(location_handler::update_location_boundary))
            .route("/location-boundaries/{location_id}", web::delete().to(location_handler::delete_location_boundary)),
    );
}
