use actix_web::web;
use crate::handlers::{attendance_handler, auth_handler, dashboard_handler, employee_handler, health_handler, leave_handler, location_handler, patrol_handler, shift_handler, wifi_handler};

pub fn init_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api")
            .route("/health", web::get().to(health_handler::health_check))
            .route("/login", web::post().to(auth_handler::login))
            .route("/register", web::post().to(auth_handler::register))
            .route("/attendance/enrollment-status", web::post().to(attendance_handler::check_enrollment))
            .route("/attendance/enroll-face", web::post().to(attendance_handler::enroll_face))
            .route("/attendance/enroll-fingerprint", web::post().to(attendance_handler::enroll_fingerprint))
            .route("/attendance/clock-in", web::post().to(attendance_handler::clock_in))
            .route("/attendance/logs", web::get().to(attendance_handler::get_all_attendances))
            .route("/employees", web::get().to(employee_handler::get_all_employees))
            .route("/employees", web::post().to(employee_handler::create_employee))
            .route("/employees/{nik}", web::get().to(employee_handler::get_employee_by_nik))
            .route("/employees/{nik}", web::put().to(employee_handler::update_employee))
            .route("/employees/{nik}", web::delete().to(employee_handler::delete_employee))
            .route("/leave", web::post().to(leave_handler::submit_leave))
            .route("/leave", web::get().to(leave_handler::get_leaves))
            .route("/leave/status", web::put().to(leave_handler::update_leave_status))
            .route("/patrol/incident", web::post().to(patrol_handler::submit_incident))
            .route("/patrol/incidents", web::get().to(patrol_handler::get_all_incidents))
            .route("/patrol/incidents/{nik}", web::get().to(patrol_handler::get_incidents_by_nik))
            .route("/patrol/checkpoints", web::post().to(patrol_handler::create_checkpoint))
            .route("/patrol/checkpoints", web::get().to(patrol_handler::get_checkpoints))
            .route("/patrol/checkpoints/{id}", web::put().to(patrol_handler::update_checkpoint))
            .route("/patrol/checkpoints/{id}", web::delete().to(patrol_handler::delete_checkpoint))
            .route("/patrol/assignments", web::post().to(patrol_handler::create_patrol_assignment))
            .route("/patrol/assignments", web::get().to(patrol_handler::get_patrol_assignments))
            .route("/patrol/assignments/{id}", web::put().to(patrol_handler::update_patrol_assignment))
            .route("/patrol/assignments/{id}", web::delete().to(patrol_handler::delete_patrol_assignment))
            .route("/patrol/status/active", web::get().to(patrol_handler::get_active_patrol_status))
            .route("/patrol/tracking/live", web::get().to(patrol_handler::get_live_tracking))
            .route("/shift", web::post().to(shift_handler::create_shift))
            .route("/shift/list", web::post().to(shift_handler::get_shifts))
            .route("/shift/all", web::get().to(shift_handler::get_all_shifts))
            .route("/shift/status", web::put().to(shift_handler::update_shift_status))
            .route("/shift/stats/{nik}", web::get().to(shift_handler::get_shift_stats))
            .route("/shift/{shift_id}", web::delete().to(shift_handler::delete_shift))
            // Dashboard Analytics Routes
            .route("/dashboard/analytics", web::get().to(dashboard_handler::get_dashboard_analytics))
            .route("/dashboard/overview", web::get().to(dashboard_handler::get_overview_only))
            .route("/dashboard/attendance", web::get().to(dashboard_handler::get_attendance_analytics))
            .route("/dashboard/patrol", web::get().to(dashboard_handler::get_patrol_analytics))
            .route("/dashboard/incidents", web::get().to(dashboard_handler::get_incident_analytics))
            .route("/dashboard/performance", web::get().to(dashboard_handler::get_performance_analytics))
            .route("/dashboard/locations", web::get().to(dashboard_handler::get_location_analytics))
            // WiFi Validation Routes
            .route("/wifi-settings", web::get().to(wifi_handler::get_wifi_settings))
            .route("/wifi-settings/all", web::get().to(wifi_handler::get_all_wifi_settings))
            .route("/wifi-settings/validate", web::post().to(wifi_handler::validate_wifi_ssid))
            .route("/wifi-settings", web::post().to(wifi_handler::create_wifi_setting))
            .route("/wifi-settings/{wifi_id}", web::patch().to(wifi_handler::update_wifi_setting))
            .route("/wifi-settings/{wifi_id}", web::delete().to(wifi_handler::delete_wifi_setting))
            // Location Boundary Routes
            .route("/location-boundaries", web::get().to(location_handler::get_location_boundaries))
            .route("/location-boundaries/all", web::get().to(location_handler::get_all_location_boundaries))
            .route("/location-boundaries/validate", web::post().to(location_handler::validate_location))
            .route("/location-boundaries", web::post().to(location_handler::create_location_boundary))
            .route("/location-boundaries/{location_id}", web::patch().to(location_handler::update_location_boundary))
            .route("/location-boundaries/{location_id}", web::delete().to(location_handler::delete_location_boundary)),
    );
}
